package me.anhnguyen.atmfinder.model.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "ATM".
 */
public class Atm {

    private Long id;
    private String name;
    private String address;
    private Double lat;
    private Double lon;

    public Atm() {
    }

    public Atm(Long id) {
        this.id = id;
    }

    public Atm(Long id, String name, String address, Double lat, Double lon) {
        this.id = id;
        this.name = name;
        this.address = address;
        this.lat = lat;
        this.lon = lon;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getAddress() {
        return address;
    }

    public void setAddress(String address) {
        this.address = address;
    }

    public Double getLat() {
        return lat;
    }

    public void setLat(Double lat) {
        this.lat = lat;
    }

    public Double getLon() {
        return lon;
    }

    public void setLon(Double lon) {
        this.lon = lon;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof Atm)) return false;

        Atm atm = (Atm) o;

        if (getId() != null ? !getId().equals(atm.getId()) : atm.getId() != null) return false;
        if (getName() != null ? !getName().equals(atm.getName()) : atm.getName() != null)
            return false;
        if (getAddress() != null ? !getAddress().equals(atm.getAddress()) : atm.getAddress() != null)
            return false;
        if (getLat() != null ? !getLat().equals(atm.getLat()) : atm.getLat() != null) return false;
        return !(getLon() != null ? !getLon().equals(atm.getLon()) : atm.getLon() != null);

    }

    @Override
    public int hashCode() {
        int result = getId() != null ? getId().hashCode() : 0;
        result = 31 * result + (getName() != null ? getName().hashCode() : 0);
        result = 31 * result + (getAddress() != null ? getAddress().hashCode() : 0);
        result = 31 * result + (getLat() != null ? getLat().hashCode() : 0);
        result = 31 * result + (getLon() != null ? getLon().hashCode() : 0);
        return result;
    }
}
