package me.anhnguyen.atmfinder.model.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import me.anhnguyen.atmfinder.model.dao.Atm;

import me.anhnguyen.atmfinder.model.dao.AtmDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig atmDaoConfig;

    private final AtmDao atmDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        atmDaoConfig = daoConfigMap.get(AtmDao.class).clone();
        atmDaoConfig.initIdentityScope(type);

        atmDao = new AtmDao(atmDaoConfig, this);

        registerDao(Atm.class, atmDao);
    }
    
    public void clear() {
        atmDaoConfig.getIdentityScope().clear();
    }

    public AtmDao getAtmDao() {
        return atmDao;
    }

}
